# Generated by Django 5.2.1 on 2025-05-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sound_activities/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='sound_activities/audio/')),
                ('type', models.CharField(choices=[('beginning', 'Beginning'), ('middle', 'Middle'), ('ending', 'Ending')], max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_activities', to='core.category')),
            ],
        ),
    ]
