# Generated by Django 5.2.1 on 2025-05-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0002_blend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blend',
            name='name',
        ),
    ]
