# Generated by Django 5.2.1 on 2025-05-17 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0003_remove_blend_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blend_fors', to='phonics.blend')),
            ],
        ),
    ]
