# Generated by Django 5.2.1 on 2025-05-17 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0004_blendfor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blend_words/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='blend_words/audio/')),
                ('blend_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blend_words', to='phonics.blendfor')),
            ],
        ),
    ]
