# Generated by Django 5.2.1 on 2025-05-17 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('phonics', '0005_blendword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rhyming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhyming', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='RhymingFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhyming_fors', to='phonics.rhyming')),
            ],
        ),
        migrations.CreateModel(
            name='RhymingWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='rhyming_words/audio/')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rhyming_words', to='phonics.rhymingfor')),
            ],
        ),
    ]
