# Generated by Django 5.2.1 on 2025-05-17 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('phonics', '0007_rhymingword_rhyming_for_alter_rhymingword_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrickyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('audio', models.FileField(blank=True, null=True, upload_to='tricky_words/audio/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tricky_words', to='core.category')),
            ],
        ),
    ]
