# Generated by Django 5.2.1 on 2025-05-17 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('phonics', '0008_trickyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadAndListen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='read_and_listen/audio/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_and_listen', to='core.category')),
            ],
        ),
    ]
