# Generated by Django 5.2.1 on 2025-05-17 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('phonics', '0009_readandlisten'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeSpelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_spellings', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeSpellingWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='alternative_spelling/images/')),
                ('answer', models.CharField(max_length=255)),
                ('audio', models.FileField(blank=True, null=True, upload_to='alternative_spelling/audio/')),
                ('alternative_spelling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_spelling_words', to='phonics.alternativespelling')),
            ],
        ),
    ]
