# Generated by Django 5.2.1 on 2025-05-17 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('phonics', '0010_alternativespelling_alternativespellingword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_fors', to='phonics.phase')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='phase_words/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='phase_words/audio/')),
                ('phase_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_words', to='phonics.phasefor')),
            ],
        ),
    ]
