# Generated by Django 5.2.1 on 2025-05-17 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('phonics', '0011_phase_phasefor_phaseword'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='identify_words/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='identify_words/audio/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identify_words', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='IdentifyWordOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('identify_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='phonics.identifywords')),
            ],
        ),
    ]
