# Generated by Django 5.2.1 on 2025-05-17 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0012_identifywords_identifywordoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vowel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], max_length=10)),
                ('audio', models.FileField(blank=True, null=True, upload_to='vowels/audio/')),
                ('sentence', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VowelWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vowel_words/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='vowel_words/audio/')),
                ('vowel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vowel_words', to='phonics.vowel')),
            ],
        ),
    ]
