# Generated by Django 5.2.1 on 2025-05-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0013_vowel_vowelword'),
    ]

    operations = [
        migrations.CreateModel(
            name='VowelsAlphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vowel', models.CharField(choices=[('a', 'a'), ('e', 'e'), ('i', 'i'), ('u', 'u'), ('ai', 'ai'), ('ee', 'ee'), ('ie', 'ie'), ('oa', 'oa'), ('ue', 'ue')], max_length=2, unique=True)),
                ('main_type', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], max_length=10)),
                ('audio', models.FileField(blank=True, null=True, upload_to='vowels_alphabet/audio/')),
            ],
        ),
    ]
