# Generated by Django 5.2.1 on 2025-05-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0014_vowelsalphabet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vowelsalphabet',
            name='word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
