# Generated by Django 5.2.1 on 2025-05-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0015_vowelsalphabet_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishAlphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=1, unique=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='english_alphabet/audio/')),
            ],
        ),
    ]
