# Generated by Django 5.2.1 on 2025-05-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonics', '0016_englishalphabet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vowelsalphabet',
            name='vowel',
            field=models.CharField(choices=[('a', 'a'), ('e', 'e'), ('i', 'i'), ('u', 'u'), ('ai', 'ai'), ('ee', 'ee'), ('ie', 'ie'), ('oa', 'oa'), ('ue', 'ue')], max_length=2),
        ),
    ]
