# Generated by Django 5.2 on 2025-04-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('classification_type', models.CharField(choices=[('grade', 'Grade Wise'), ('level', 'Level Wise'), ('none', 'None/Direct')], max_length=10)),
            ],
        ),
    ]
