# Generated by Django 5.2.1 on 2025-05-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='allowed_categories', to='auth.group'),
        ),
    ]
