# Generated by Django 5.2.1 on 2025-05-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_allowed_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='allowed_groups',
        ),
    ]
