# Generated by Django 5.2.1 on 2025-05-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
