# Generated by Django 5.2.1 on 2025-05-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarquestion',
            name='activity_type',
        ),
        migrations.AlterField(
            model_name='grammartype',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='grammartype',
            unique_together={('category', 'name')},
        ),
        migrations.DeleteModel(
            name='GrammarActivityType',
        ),
    ]
