# Generated by Django 5.2.1 on 2025-05-12 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0003_grammaractivity_grammarcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarquestion',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='grammarquestion',
            name='answer',
        ),
        migrations.AlterField(
            model_name='grammarcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GrammarSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='grammar.grammarcategory')),
            ],
        ),
        migrations.AddField(
            model_name='grammarquestion',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='grammar.grammarsubcategory'),
        ),
        migrations.DeleteModel(
            name='GrammarActivity',
        ),
    ]
