# Generated by Django 5.2.1 on 2025-05-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0004_remove_grammarquestion_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='grammarsubcategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='grammarquestion',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='grammar.grammarsubcategory'),
        ),
        migrations.AlterField(
            model_name='grammarsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='grammar.grammarcategory'),
        ),
    ]
