# Generated by Django 5.2.1 on 2025-05-12 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0005_remove_grammarcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grammarsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='grammar.grammarcategory'),
        ),
        migrations.AlterField(
            model_name='grammarsubcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
