# Generated by Django 5.2.1 on 2025-05-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('grammar', '0006_alter_grammarcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_categories', to='core.category'),
        ),
    ]
