# Generated by Django 5.2.1 on 2025-05-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0007_grammarcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarquestion',
            name='sub_category',
        ),
        migrations.CreateModel(
            name='GrammarActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='grammar.grammarcategory')),
            ],
        ),
        migrations.AddField(
            model_name='grammarquestion',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='grammar.grammaractivity'),
        ),
        migrations.DeleteModel(
            name='GrammarSubCategory',
        ),
    ]
