# Generated by Django 5.2.1 on 2025-05-12 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0008_remove_grammarquestion_sub_category_grammaractivity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='grammar.grammarcategory')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('grammar_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='grammar.grammartype')),
            ],
        ),
    ]
