# Generated by Django 5.2.1 on 2025-05-12 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0009_grammartype_grammarword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammartype',
            name='category',
        ),
        migrations.CreateModel(
            name='DragDropActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_drop_activities', to='grammar.grammarcategory')),
            ],
        ),
        migrations.AddField(
            model_name='grammartype',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='grammar.dragdropactivity'),
        ),
    ]
