# Generated by Django 5.2.1 on 2025-05-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0011_remove_grammarword_grammar_type_delete_grammartype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragdropactivity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dragdrop_activities', to='grammar.grammarcategory'),
        ),
        migrations.CreateModel(
            name='DragDropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='grammar.dragdropactivity')),
            ],
        ),
        migrations.CreateModel(
            name='DragDropWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('dragdrop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='grammar.dragdroptype')),
            ],
        ),
    ]
