# Generated by Django 5.2.1 on 2025-05-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0012_alter_dragdropactivity_category_dragdroptype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragdroptype',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grammar.dragdropactivity'),
        ),
    ]
