# Generated by Django 5.2.1 on 2025-05-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('grammar', '0013_alter_dragdroptype_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickWordsActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickwords_activities', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='PickWordsSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='grammar.pickwordsactivity')),
            ],
        ),
        migrations.CreateModel(
            name='PickWordsWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='grammar.pickwordssentence')),
            ],
        ),
    ]
