# Generated by Django 5.2.1 on 2025-05-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0014_pickwordsactivity_pickwordssentence_pickwordsword'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
