# Generated by Django 5.2.1 on 2025-05-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0015_grammarcategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grammarcategory',
            old_name='name',
            new_name='title',
        ),
    ]
