# Generated by Django 5.2.1 on 2025-05-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0016_rename_name_grammarcategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragdropactivity',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
