# Generated by Django 5.2.1 on 2025-05-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0017_dragdropactivity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickwordsactivity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickwords_activities', to='grammar.grammarcategory'),
        ),
    ]
