# Generated by Django 5.2.1 on 2025-05-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('reading', '0003_matchingpair'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spelling_types', to='core.category')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spelling_types', to='reading.reading')),
            ],
        ),
        migrations.CreateModel(
            name='SpellingWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/spelling_words/')),
                ('spelling_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='activity.spellingtype')),
            ],
        ),
    ]
