# Generated by Django 5.2.1 on 2025-05-12 09:01

import activity.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_spellingtype_reading'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spellingtype',
            name='category',
        ),
        migrations.CreateModel(
            name='SpellingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spelling_groups', to='core.category')),
            ],
        ),
        migrations.AddField(
            model_name='spellingtype',
            name='group',
            field=models.ForeignKey(default=activity.models.get_default_group, on_delete=django.db.models.deletion.CASCADE, related_name='spelling_types', to='activity.spellinggroup'),
        ),
        migrations.DeleteModel(
            name='SpellingWord',
        ),
    ]
