# Generated by Django 5.2.1 on 2025-05-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_remove_spellingtype_category_spellinggroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellingWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/spelling_words/')),
                ('spelling_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='activity.spellingtype')),
            ],
        ),
    ]
