# Generated by Django 5.2.1 on 2025-05-12 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_longvowelsound'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnscrambleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_part_1', models.TextField(help_text='Sentence part before the blank space')),
                ('sentence_part_2', models.TextField(help_text='Sentence part after the blank space')),
                ('word', models.CharField(max_length=100)),
                ('scrambled_word', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/unscramble_activities/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unscramble_activities', to='core.category')),
            ],
        ),
    ]
