# Generated by Django 5.2.1 on 2025-05-12 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_unscrambleactivity'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expression_groups', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/expression_objects/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expression_objects', to='activity.expressiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('expression_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='activity.expressionobject')),
            ],
        ),
    ]
