# Generated by Django 5.2.1 on 2025-05-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_expressiongroup_expressionobject_expressionoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressionobject',
            name='expression',
        ),
    ]
