# Generated by Django 5.2.1 on 2025-05-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_remove_expressionobject_expression'),
    ]

    operations = [
        migrations.CreateModel(
            name='VowelWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('vowel_type', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], default='short', max_length=5)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/vowel_words/')),
            ],
        ),
    ]
