# Generated by Django 5.2 on 2025-04-16 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_truefalseactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('response', models.CharField(max_length=255)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='reading.reading')),
            ],
        ),
    ]
