# Generated by Django 5.2.1 on 2025-05-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_matchingpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reading/images/'),
        ),
    ]
