# Generated by Django 5.2.1 on 2025-05-14 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='missing_words/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_words', to='core.category')),
            ],
        ),
    ]
