# Generated by Django 5.2.1 on 2025-05-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_optionanswer_genericactivity_identifypicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifypicture',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_answers', to='vocabulary.optionanswer'),
        ),
        migrations.AlterField(
            model_name='genericactivity',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='identifypicture',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='vocabulary.genericactivity'),
        ),
        migrations.AlterField(
            model_name='identifypicture',
            name='image',
            field=models.ImageField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='identifypicture',
            name='options',
            field=models.ManyToManyField(related_name='pictures', to='vocabulary.optionanswer'),
        ),
    ]
