# Generated by Django 5.2.1 on 2025-05-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_identifypicture_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identifypicture',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='identifypicture',
            name='options',
        ),
        migrations.AddField(
            model_name='optionanswer',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='vocabulary.identifypicture'),
        ),
    ]
