# Generated by Django 5.2.1 on 2025-05-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vocabulary', '0004_remove_identifypicture_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericactivity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.category'),
        ),
    ]
