# Generated by Django 5.2.1 on 2025-05-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_alter_genericactivity_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMatchingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_matching_activities', to='vocabulary.genericactivity')),
            ],
        ),
        migrations.CreateModel(
            name='ImageWordPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='image_matching/')),
                ('word_1', models.CharField(max_length=255)),
                ('image_2', models.ImageField(upload_to='image_matching/')),
                ('word_2', models.CharField(max_length=255)),
                ('image_matching_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_word_pairs', to='vocabulary.imagematchingactivity')),
            ],
        ),
    ]
