# Generated by Django 5.2.1 on 2025-05-15 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0006_imagematchingactivity_imagewordpair'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynonymAntonymActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonym_antonym_activities', to='vocabulary.genericactivity')),
            ],
        ),
        migrations.CreateModel(
            name='WordPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_word', models.CharField(max_length=255)),
                ('word_1', models.CharField(max_length=255)),
                ('word_2', models.CharField(max_length=255)),
                ('word_type', models.CharField(choices=[('synonym', 'Synonym'), ('antonym', 'Antonym')], max_length=10)),
                ('synonym_antonym_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_pairs', to='vocabulary.synonymantonymactivity')),
            ],
        ),
    ]
