# Generated by Django 5.2.1 on 2025-05-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0007_synonymantonymactivity_wordpair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordpair',
            name='word_type',
        ),
    ]
