# Generated by Django 5.2.1 on 2025-05-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0008_remove_wordpair_word_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordpair',
            old_name='word_1',
            new_name='antonym',
        ),
        migrations.RenameField(
            model_name='wordpair',
            old_name='word_2',
            new_name='synonym',
        ),
    ]
