# Generated by Django 5.2.1 on 2025-05-15 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0009_rename_word_1_wordpair_antonym_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefixSuffixActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefix_suffix_activities', to='vocabulary.genericactivity')),
            ],
        ),
        migrations.CreateModel(
            name='PrefixSuffixWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('prefix_option', models.CharField(blank=True, max_length=255, null=True)),
                ('suffix_option', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulary.prefixsuffixactivity')),
            ],
        ),
    ]
