# Generated by Django 5.2.1 on 2025-05-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0010_prefixsuffixactivity_prefixsuffixword'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefixsuffixactivity',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prefixsuffixactivity',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prefix_suffix_activities', to='vocabulary.genericactivity'),
        ),
        migrations.CreateModel(
            name='PrefixSuffixType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('Prefix', 'Prefix'), ('Suffix', 'Suffix')], max_length=6)),
                ('activity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='vocabulary.prefixsuffixactivity')),
            ],
        ),
        migrations.CreateModel(
            name='PrefixSuffixOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('prefix_suffix_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='vocabulary.prefixsuffixtype')),
            ],
        ),
        migrations.DeleteModel(
            name='PrefixSuffixWord',
        ),
    ]
