# Generated by Django 5.2.1 on 2025-05-15 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vocabulary', '0011_prefixsuffixactivity_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefixsuffixtype',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='prefixsuffixactivity',
            name='activity',
        ),
        migrations.AddField(
            model_name='prefixsuffixactivity',
            name='type',
            field=models.CharField(choices=[('prefix', 'Prefix'), ('suffix', 'Suffix'), ('other', 'Other')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='prefixsuffixactivity',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prefix_suffix_activities', to='core.category'),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulary.prefixsuffixactivity')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('is_answer', models.BooleanField(default=False)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='vocabulary.word')),
            ],
        ),
        migrations.DeleteModel(
            name='PrefixSuffixOption',
        ),
        migrations.DeleteModel(
            name='PrefixSuffixType',
        ),
    ]
