# Generated by Django 5.2.1 on 2025-05-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0012_remove_prefixsuffixtype_activity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='PrefixSuffixOption',
        ),
        migrations.RenameModel(
            old_name='Word',
            new_name='PrefixSuffixWord',
        ),
    ]
