# Generated by Django 5.2.1 on 2025-05-15 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vocabulary', '0013_rename_option_prefixsuffixoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnscrambleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sentence', 'Sentence'), ('word', 'Word')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_unscramble_activities', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='UnscrambleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vocabulary.unscrambleactivity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
