# Generated by Django 5.2.1 on 2025-05-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0014_unscrambleactivity_unscrambleentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unscrambleentry',
            options={},
        ),
        migrations.RemoveField(
            model_name='unscrambleentry',
            name='order',
        ),
    ]
