# Generated by Django 5.2.1 on 2025-05-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0015_alter_unscrambleentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericactivity',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
