# Generated by Django 5.2.1 on 2025-05-23 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0016_genericactivity_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingword',
            name='category',
        ),
        migrations.AddField(
            model_name='missingword',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_words', to='vocabulary.genericactivity'),
        ),
    ]
