# Generated by Django 5.2.1 on 2025-05-23 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0017_remove_missingword_category_missingword_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prefixsuffixword',
            old_name='activity',
            new_name='prefix_suffix_activity',
        ),
        migrations.RemoveField(
            model_name='prefixsuffixactivity',
            name='category',
        ),
        migrations.AddField(
            model_name='prefixsuffixactivity',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefix_suffix_activities', to='vocabulary.genericactivity'),
        ),
    ]
