# Generated by Django 5.2.1 on 2025-05-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0018_rename_activity_prefixsuffixword_prefix_suffix_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefixsuffixword',
            name='word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
