# Generated by Django 5.2.1 on 2025-05-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0019_prefixsuffixword_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unscrambleactivity',
            name='category',
        ),
        migrations.AddField(
            model_name='unscrambleactivity',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unscramble_activities', to='vocabulary.genericactivity'),
        ),
    ]
