# Generated by Django 5.2.1 on 2025-05-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0020_remove_unscrambleactivity_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crosswords', to='vocabulary.genericactivity')),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('across', 'Across'), ('down', 'Down')], max_length=6)),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('crossword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='vocabulary.crossword')),
            ],
        ),
        migrations.CreateModel(
            name='CrosswordCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('letter', models.CharField(blank=True, max_length=1, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_black', models.BooleanField(default=False)),
                ('crossword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='vocabulary.crossword')),
            ],
        ),
    ]
